import random
import operator #for primitives
import math #to calculate the statistics
import functools #for premitives

from deap import base, creator, tools, gp

# Define the symbolic regression function
def symbolic_regression(x):
    return 5 * x**3 - 6 * x**2 + 8 * x


# calculates the Root Mean Square Error (RMSE) between the 
# symbolic regression function and the individual's expression generated by GP.
# The lower the RMSE, the better the individual approximates the desired symbolic regression function.
def eval_rmse(individual, points):
    symbolic_expr = toolbox.compile(expr=individual)
    rmse = math.sqrt(sum((symbolic_expr(x) - symbolic_regression(x))**2 for x in points) / len(points))
    return rmse,

#  Defines the set of primitive functions and constants that can 
# be used to create the expressions (programs) in the GP tree
pset = gp.PrimitiveSet("MAIN", arity=1)
pset.addPrimitive(operator.add, arity=2)
pset.addPrimitive(operator.sub, arity=2)
pset.addPrimitive(operator.mul, arity=2)
pset.addPrimitive(operator.neg, arity=1)
pset.addPrimitive(math.sin, arity=1)
pset.addPrimitive(math.cos, arity=1)
pset.addPrimitive(math.tan, arity=1)
pset.addEphemeralConstant("const", functools.partial(random.randint, -10, 10))

# Define the Fitness Function to select the best fit 
creator.create("FitnessMin", base.Fitness, weights=(-1.0,))
creator.create("Individual", gp.PrimitiveTree, fitness=creator.FitnessMin)

# Create the Toolbox to use the functions
toolbox = base.Toolbox()
toolbox.register("expr", gp.genHalfAndHalf, pset=pset, min_=1, max_=3)
toolbox.register("individual", tools.initIterate, creator.Individual, toolbox.expr)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)
toolbox.register("compile", gp.compile, pset=pset)
toolbox.register("evaluate", eval_rmse, points=[x for x in range(-10, 11)])
toolbox.register("select", tools.selTournament, tournsize=3)
toolbox.register("mate", gp.cxOnePoint)
toolbox.register("mutate", gp.mutNodeReplacement, pset=pset)

# Define Parameters
pop_size = 500 #to define the population
num_generations = 10

# Create Initial Population
population = toolbox.population(n=pop_size)

# Evolutionary Loop
for gen in range(num_generations):
    # Evaluate the population
    fitnesses = toolbox.map(toolbox.evaluate, population)
    for ind, fit in zip(population, fitnesses):
        ind.fitness.values = fit

    # Select the next generation individuals
    offspring = toolbox.select(population, len(population))

    # Clone the selected individuals
    offspring = list(map(toolbox.clone, offspring))

    # Apply crossover(mate) and mutation
    for child1, child2 in zip(offspring[::2], offspring[1::2]):
        if random.random() < 0.5:
            toolbox.mate(child1, child2)
            del child1.fitness.values
            del child2.fitness.values

    for mutant in offspring:
        if random.random() < 0.2:
            toolbox.mutate(mutant)
            del mutant.fitness.values

    # Replace the population with the offspring
    population[:] = offspring

    # Gather all the fitnesses in one list
    fits = [ind.fitness.values[0] if ind.fitness.valid else None for ind in population]
    mean = sum(fit for fit in fits if fit is not None) / len(population)
    std = math.sqrt(sum((fit - mean)**2 for fit in fits if fit is not None) / len(population))
    print(f"- Generation {gen+1}\n")
    print(f"Evaluated {len(population)} individuals")
    print(f"Min = {min(fit for fit in fits if fit is not None)} , Max = {max(fit for fit in fits if fit is not None)}")
    print(f"Average = {round(mean, 2)} , Standard deviation = {round(std, 2)}\n")

# Select the best individual
best_ind = tools.selBest(population, 1)[0]
print("- Evolution ends\n")
print("Best individual:")
print(str(best_ind))
